# Generated by Django 4.2.7 on 2023-12-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_taken", models.DateField()),
                ("film_type", models.CharField(max_length=50)),
                ("camera", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="photos/")),
            ],
        ),
    ]
